import Head from "next/head";
// import Image from "next/image";
import Hero from "../components/home/Hero";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
      </main>

      <footer className=""></footer>
    </div>
  );
}
