import Head from "next/head";
import FAQ from "../components/home/FAQ";
// import Image from "next/image";
import Hero from "../components/home/Hero";
import Packages from "../components/home/Packages";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <Packages />
        <FAQ/>
      </main>

      <footer className=""></footer>
    </div>
  );
}
